# Generated by Django 2.0 on 2018-12-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aceito',
            field=models.BooleanField(default=False, verbose_name='Aceito'),
        ),
    ]
