# Generated by Django 2.0 on 2018-12-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0003_post_palavras_chave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='resumo',
            field=models.CharField(max_length=10000, verbose_name='Resumo'),
        ),
    ]
