# Generated by Django 2.0 on 2018-12-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0006_auto_20181209_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/%Y/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/%Y/', verbose_name='Foto'),
        ),
    ]
