# Generated by Django 2.0 on 2018-11-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_choices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
    ]
